name: Install dependencies


runs:
  using: composite
  steps:
      - name: Install and upgrade pip
        shell: bash -el {0}
        run: |
          apt-get update
          apt-get install -y python3-pip
          python3 -m pip install -U pip

      - name: Install MPICH
        shell: bask -el {0}
        run: |
          apt-get install -y libmpich-dev

      - name: Install requirements
        shell: bash -el {0}
        run: |
          python3 -m pip install -r requirements.txt