name: Install dependencies

inputs:
  python-version:
    description: Python version to install
    required: true
    type: string
    default: "3.10"

runs:
  using: composite
  steps:
    - name: Setup conda-forge
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: mpi-tutorial
          python-version: ${{ inputs.python-version }}
          use-mamba: true
          environment-file: environment.yml

    # - name: Prepare cache
    #   shell: bash -el {0}
    #   run: |
    #     if [[ $CONDA != /opt/conda ]]; then
    #       mkdir -p /opt/conda/
    #       ln -s $CONDA/envs /opt/conda/envs
    #     fi
    #     echo CONDA=$CONDA
    #     mamba env list
        
    # - name: Environment cache
    #   uses: actions/cache@v3
    #   with:
    #     path: /opt/conda/envs/mpi-tutorial
    #     key: env-conda-mpi-tutorial-${{ inputs.python-version }}-${{ hashFiles('.github/actions/install-dependencies/*') }}
    #   id: cache


