name: mpi-tutorial
channels:
  - conda-forge
dependencies:
  - altair
  - mpich
  - ipyparallel
  - ipywidgets
  - jupyter-book
  - mpi4py
  - numpy
  - pandas
  - autopep8
  - fenics-dolfinx
  - pip:
    - ipyparallel>=8.6
