name: Build book

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  build-book:
    runs-on: ubuntu-latest
 
    steps:

      - uses: actions/checkout@v3
  
      - name: Install common packages
        uses: ./.github/actions/install-dependencies

      - name: Build the book
        run: 
          jupyter-book build . -W

      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ./_build/html
          retention-days: 2
          if-no-files-found: error