name: Build book

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  build-book:
    runs-on: ubuntu-latest
   
    env:
      PYVISTA_TRAME_SERVER_PROXY_PREFIX: '/proxy/'
      PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "panel"

    steps:

      - uses: actions/checkout@v3
  
      - name: Install common packages
        uses: ./.github/actions/install-dependencies

      - name: Install book deps
        run:
          python3 -m pip install -r requirements.txt

      - name: Build the book
        run: 
          jupyter-book build . -W

      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ./_build/html
          retention-days: 2
          if-no-files-found: error